var assert = require('assert')
var decode = require('../decode')
var u8a = require('u8a/from-string')

assert.deepEqual(decode(u8a('ME======')), u8a('a'))
assert.deepEqual(decode(u8a('MJSQ====')), u8a('be'))
assert.deepEqual(decode(u8a('ONXW4===')), u8a('son'))
assert.deepEqual(decode(u8a('MJSWK===')), u8a('bee'))
assert.deepEqual(decode(u8a('MJSWK4Q=')), u8a('beer'))
assert.deepEqual(decode(u8a('MJSWK4TT')), u8a('beers'))
assert.deepEqual(decode(u8a('mjswK4TT')), u8a('beers'))
assert.deepEqual(decode(u8a('MJSWK4TTN5XA====')), u8a('beerson'))
assert.deepEqual(decode(u8a('MJSWK4TTEAYQ====')), u8a('beers 1'))
assert.deepEqual(decode(u8a('ONUG6Y3LNFXGO3DZEBSGS43NNFZXGZLE')), u8a('shockingly dismissed'))
